# Versionamento no flyway
#  <V><ano><mês><dia><hora_24h><minuto>.<versão>_<atualização>__<descrição do script>.sql

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
      testOnBorrow: true
